### ISSUE TITLE
Not show player

### ISSUE THREAD

**Issue by rclabs-dev** [davidNHK/spotify-music-player#475]
Hi dear,

Congratulations!

I downloaded your code and I trying to test and I authorize it on spotify; after this, show the a good screen, but when I click on my library, the playlist didn't show in the right side. It already working at this point? I received only this message: "Page should display track under playlistId : 2gRmXMkkzhlZ3BCSTW8ldt" the right side screen is black.

Thanks in advance.

Best regards.

**Comment by davidnghk01** [comment]
Hi , this project is still under development.

For the `track` under `playlist` i still working on [This PR](https://github.com/davidNHK/spotify-music-player/pull/462)

Thanks for your test my project :)

**Comment by rclabs-dev** [comment]
> Hi , this project is still under development.
> 
> For the `track` under `playlist` i still working on [This PR](https://github.com/davidNHK/spotify-music-player/pull/462)
> 
> Thanks for your test my project :)

Thank you for your reply. Ok! It's getting really good.
I would like to know when it will be ok for the test, if possible.

Thanks in advance.

Best regards!

**Comment by davidNHK** [comment]
Hi, sorry for late response

Actually, i don't have deadline for that , and it has lot of to do things before said it done.
